### ISSUE TITLE
Why not NCCL?

### ISSUE THREAD

**Issue by cliffwoolley** [baidu-research/baidu-allreduce#1]
What's the benefit of using this implementation as opposed to using NCCL?

**Comment by cliffwoolley** [comment]
https://github.com/NVIDIA/nccl
http://images.nvidia.com/events/sc15/pdfs/NCCL-Woolley.pdf

**Comment by gibiansky** [comment]
As far as I know, NCCL is meant to be used on a single node. Using an MPI-based allreduce allows you to use multiple nodes, and use Infiniband connections between the nodes and PCIe connections within the nodes.

**Comment by cliffwoolley** [comment]
I guess the debate is whether the GPU-aware part of the collective should be built on top of or underneath of MPI.  In my experience, building on top of MPI (using MPI_Send/MPI_Recv) means that the achievable bandwidth for small collectives is fairly low due to the high latency of beginning each bulk transfer.

Does this match your experience?

**Comment by shubho** [comment]
Yes this is not the way to build collectives for small data. This is only used for large matrices - at least 1024 x 1024 float32
